// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package hxgm30.proto.buf.common;

/**
 * <pre>
 * HealthReply ...
 * </pre>
 *
 * Protobuf type {@code common.HealthReply}
 */
public  final class HealthReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:common.HealthReply)
    HealthReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HealthReply.newBuilder() to construct.
  private HealthReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HealthReply() {
    components_ = "";
    errors_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HealthReply();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HealthReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            components_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            errors_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return hxgm30.proto.buf.common.CommonProto.internal_static_common_HealthReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return hxgm30.proto.buf.common.CommonProto.internal_static_common_HealthReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            hxgm30.proto.buf.common.HealthReply.class, hxgm30.proto.buf.common.HealthReply.Builder.class);
  }

  public static final int COMPONENTS_FIELD_NUMBER = 1;
  private volatile java.lang.Object components_;
  /**
   * <code>string components = 1;</code>
   * @return The components.
   */
  public java.lang.String getComponents() {
    java.lang.Object ref = components_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      components_ = s;
      return s;
    }
  }
  /**
   * <code>string components = 1;</code>
   * @return The bytes for components.
   */
  public com.google.protobuf.ByteString
      getComponentsBytes() {
    java.lang.Object ref = components_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      components_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ERRORS_FIELD_NUMBER = 2;
  private volatile java.lang.Object errors_;
  /**
   * <code>string errors = 2;</code>
   * @return The errors.
   */
  public java.lang.String getErrors() {
    java.lang.Object ref = errors_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errors_ = s;
      return s;
    }
  }
  /**
   * <code>string errors = 2;</code>
   * @return The bytes for errors.
   */
  public com.google.protobuf.ByteString
      getErrorsBytes() {
    java.lang.Object ref = errors_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errors_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getComponentsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, components_);
    }
    if (!getErrorsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errors_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getComponentsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, components_);
    }
    if (!getErrorsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errors_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof hxgm30.proto.buf.common.HealthReply)) {
      return super.equals(obj);
    }
    hxgm30.proto.buf.common.HealthReply other = (hxgm30.proto.buf.common.HealthReply) obj;

    if (!getComponents()
        .equals(other.getComponents())) return false;
    if (!getErrors()
        .equals(other.getErrors())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMPONENTS_FIELD_NUMBER;
    hash = (53 * hash) + getComponents().hashCode();
    hash = (37 * hash) + ERRORS_FIELD_NUMBER;
    hash = (53 * hash) + getErrors().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.proto.buf.common.HealthReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static hxgm30.proto.buf.common.HealthReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static hxgm30.proto.buf.common.HealthReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(hxgm30.proto.buf.common.HealthReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * HealthReply ...
   * </pre>
   *
   * Protobuf type {@code common.HealthReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:common.HealthReply)
      hxgm30.proto.buf.common.HealthReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hxgm30.proto.buf.common.CommonProto.internal_static_common_HealthReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hxgm30.proto.buf.common.CommonProto.internal_static_common_HealthReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hxgm30.proto.buf.common.HealthReply.class, hxgm30.proto.buf.common.HealthReply.Builder.class);
    }

    // Construct using hxgm30.proto.buf.common.HealthReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      components_ = "";

      errors_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return hxgm30.proto.buf.common.CommonProto.internal_static_common_HealthReply_descriptor;
    }

    @java.lang.Override
    public hxgm30.proto.buf.common.HealthReply getDefaultInstanceForType() {
      return hxgm30.proto.buf.common.HealthReply.getDefaultInstance();
    }

    @java.lang.Override
    public hxgm30.proto.buf.common.HealthReply build() {
      hxgm30.proto.buf.common.HealthReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public hxgm30.proto.buf.common.HealthReply buildPartial() {
      hxgm30.proto.buf.common.HealthReply result = new hxgm30.proto.buf.common.HealthReply(this);
      result.components_ = components_;
      result.errors_ = errors_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof hxgm30.proto.buf.common.HealthReply) {
        return mergeFrom((hxgm30.proto.buf.common.HealthReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(hxgm30.proto.buf.common.HealthReply other) {
      if (other == hxgm30.proto.buf.common.HealthReply.getDefaultInstance()) return this;
      if (!other.getComponents().isEmpty()) {
        components_ = other.components_;
        onChanged();
      }
      if (!other.getErrors().isEmpty()) {
        errors_ = other.errors_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      hxgm30.proto.buf.common.HealthReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (hxgm30.proto.buf.common.HealthReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object components_ = "";
    /**
     * <code>string components = 1;</code>
     * @return The components.
     */
    public java.lang.String getComponents() {
      java.lang.Object ref = components_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        components_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string components = 1;</code>
     * @return The bytes for components.
     */
    public com.google.protobuf.ByteString
        getComponentsBytes() {
      java.lang.Object ref = components_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        components_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string components = 1;</code>
     * @param value The components to set.
     * @return This builder for chaining.
     */
    public Builder setComponents(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      components_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string components = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearComponents() {
      
      components_ = getDefaultInstance().getComponents();
      onChanged();
      return this;
    }
    /**
     * <code>string components = 1;</code>
     * @param value The bytes for components to set.
     * @return This builder for chaining.
     */
    public Builder setComponentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      components_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object errors_ = "";
    /**
     * <code>string errors = 2;</code>
     * @return The errors.
     */
    public java.lang.String getErrors() {
      java.lang.Object ref = errors_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errors_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string errors = 2;</code>
     * @return The bytes for errors.
     */
    public com.google.protobuf.ByteString
        getErrorsBytes() {
      java.lang.Object ref = errors_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string errors = 2;</code>
     * @param value The errors to set.
     * @return This builder for chaining.
     */
    public Builder setErrors(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errors_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string errors = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearErrors() {
      
      errors_ = getDefaultInstance().getErrors();
      onChanged();
      return this;
    }
    /**
     * <code>string errors = 2;</code>
     * @param value The bytes for errors to set.
     * @return This builder for chaining.
     */
    public Builder setErrorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errors_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:common.HealthReply)
  }

  // @@protoc_insertion_point(class_scope:common.HealthReply)
  private static final hxgm30.proto.buf.common.HealthReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new hxgm30.proto.buf.common.HealthReply();
  }

  public static hxgm30.proto.buf.common.HealthReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HealthReply>
      PARSER = new com.google.protobuf.AbstractParser<HealthReply>() {
    @java.lang.Override
    public HealthReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HealthReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HealthReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HealthReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public hxgm30.proto.buf.common.HealthReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

