// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package hxgm30.proto.buf.common;

public interface HealthReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.HealthReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string components = 1;</code>
   * @return The components.
   */
  java.lang.String getComponents();
  /**
   * <code>string components = 1;</code>
   * @return The bytes for components.
   */
  com.google.protobuf.ByteString
      getComponentsBytes();

  /**
   * <code>string errors = 2;</code>
   * @return The errors.
   */
  java.lang.String getErrors();
  /**
   * <code>string errors = 2;</code>
   * @return The bytes for errors.
   */
  com.google.protobuf.ByteString
      getErrorsBytes();
}
