// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package hxgm30.proto.buf.common;

public interface PingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:common.PingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string data = 1;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
